export enum RepositoryErrorCode {
    // Sheets
    ADD_SHEET_FAILED = "ADD_SHEET_FAILED",
    GET_SHEETS_FAILED = "GET_SHEETS_FAILED",

    // Tariffs
    CREATE_UPDATE_TARIFFS_FAILED = "CREATE_UPDATE_TARIFFS_FAILED",
    GET_TARIFFS_FAILED = "GET_TARIFFS_FAILED",
}