export type Tariff = {
    id: number,
    date: number,
    dt_next_box: number | null,
    dt_till_max: number,
    box_delivery_base: number | null,
    box_delivery_coef_expr: number | null,
    box_delivery_liter: number | null,
    box_delivery_marketplace_base: number | null,
    box_delivery_marketplace_coef_expr: number | null,
    box_delivery_marketplace_liter: number | null,
    box_storage_base: number | null,
    box_storage_coef_expr: number | null,
    box_storage_liter: number | null,
    warehouse_name: string,
    geo_name: string,
    created_at: number,
    updated_at: number,
}